name: Carbyne
main: com.medievallords.carbyne.Carbyne
version: 0.3
description: Carbyne weapons and armors.
author: Dolphindalt
softdepend: [Towny, CombatTagPlus]
commands:
    cg:
        description: Main command. Stands for Carbyne Gear.
    scoreboard:
        description: Scoreboard commands.

permisions:
    carbyne.admin:
        description: Admin permissions for the entire plugin.
        default: op
    skills.ignore:
        description: Ignore all skills for staff
        default: op