name: Carbyne
main: com.medievallords.carbyne.Carbyne
version: 0.3
description: Carbyne weapons and armors.
author: Dolphindalt
softdepend: [Towny, CombatTagPlus]
commands:
    cg:
        description: Main command. Stands for Carbyne Gear.
    scoreboard:
        description: Scoreboard commands.