name: Carbyne
main: com.medievallords.carbyne.Carbyne
version: 1.0.2
description: Main core for the Medieval Lords server with carbyne weapons and armors
author: Young
depend: [MythicMobs, WorldEdit]
softdepend: [Towny]
loadBefore: [Vault]