package com.medievallords.carbyne.events;

/**
 * Created by Dalton on 7/8/2017.
 */
public enum EventProperties
{

    PVP_DISABLED, SPELLS_DISABLED, PLUGIN_TELEPORT_DISABLED, ENDERPEARL_TELEPORT_DISABLED, REMOVE_PLAYER_ON_DEATH, REMOVE_PLAYER_ON_QUIT, PREVENT_POTION_DRINKING, HUNGER_DISABLED

}
